services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - app-network
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge